language: python

python:
  - "2.7"

install: "pip install -r requirements.txt && pip install -r test-requirements.txt"
# command to run tests
script: nosetests -w ./tests/unit

notifications:
  email: false
